export const Products = [

    {
    "id": 1,
    "name": "Dog Treats for 12 months+",
    "price": 299,
    "rating": 4.9,
    "reviews": "1.2k",
    "image": "/images/dog_food1.webp",
    "originalPrice": 499,
    
    },
    {
    "id": 2,
    "name": "Pedigree Meat Jerky",
    "price": 599,
    "rating": 4.8,
    "reviews": "1.5k",
    "image": '/images/dog_food2.webp',
    "originalPrice": 799,
    },
    {
    "id": 3,
    "name": "Pet Sausage (Chicken, Duck, Beef)",
    "price": 399,
    "rating": 4.5,
    "reviews": "2.2k",
    "image": '/images/dog_food3.jpg',
    "originalPrice": 699,
    },
    {
    "id": 4,
    "name": "Blackhawk Chicken Cat Food",
    "price": 799,
    "rating": 4.9,
    "reviews": "1.5k",
    "image": '/images/cat_food1.jpg',
    "originalPrice": 999,
    },
    {
    "id": 5,
    "name": "Freeze-Dried Cat Food",
    "price": 499,
    "rating": 4.9,
    "reviews": "3.2k",
    "image": '/images/cat_food2.webp',
    "originalPrice": 899,
    },
    {
    "id": 6,
    "name": "9Lives Cat Food",
    "price": 299,
    "rating": 4.8,
    "reviews": "1.1k",
    "image": '/images/cat_food3.webp',
    "originalPrice": 499,
    },
    {
    "id": 7,
    "name": "Red pet collar",
    "price": 250,
    "rating": 4.9,
    "reviews": "5.6k",
    "image": '/images/pet_collar1.webp',
    "originalPrice": 500,
    },
    {
    "id": 8,
    "name": "Reinforced assorted pet collar",
    "price": 299,
    "rating": 4.5,
    "reviews": 120,
    "image": '/images/pet_collar3.jpg',
    "originalPrice": 499,
    },
    {
    "id": 9,
    "name": "Dog Kennel",
    "price": 699,
    "rating": 4.9,
    "reviews": "1.5k",
    "image": '/images/pet_cage1.jpg',
    "originalPrice": 1099,
    },
    {
    "id": 10,
    "name": "Rope Leash",
    "price": 299,
    "rating": 4.5,
    "reviews": "2.2k",
    "image": '/images/pet_leash1.webp',

    },
    {
    "id": 11,
    "name": "Red thin leash",
    "price": 299,
    "rating": 4.5,
    "reviews": "10.1k",
    "image": '/images/pet_leash2.webp',
    "originalPrice": 499,
    },
    {
    "id": 12,
    "name": "Body leash for Dogs and Cats",
    "price": 299,
    "rating": 4.5,
    "reviews": "7.6k",
    "image": '/images/pet_leash3.webp',
    "originalPrice": 499,
    },
]